In [1]:
from tensorflow.keras.preprocessing.text import one_hot


d:\GENAI\DeepLearning\dlenv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
# Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'Iam a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your classes are good',
      ]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'Iam a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your classes are good']

In [4]:
# Define the vocabulary size
voc_size=10000


In [6]:
# One hot representation 
one_hot_repr=[one_hot(sent, voc_size)for sent in sent]
one_hot_repr

[[958, 7186, 5673, 9502],
 [958, 7186, 5673, 8070],
 [958, 4638, 5673, 1561],
 [6707, 1049, 7952, 3962],
 [6189, 6256, 1049, 7952, 9989],
 [9618, 958, 4829, 5673, 9533],
 [8235, 6348, 1933, 7952]]

In [7]:
# word embedding representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing import pad_sequence
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  958 7186 5673 9502]
 [   0    0    0    0  958 7186 5673 8070]
 [   0    0    0    0  958 4638 5673 1561]
 [   0    0    0    0 6707 1049 7952 3962]
 [   0    0    0 6189 6256 1049 7952 9989]
 [   0    0    0 9618  958 4829 5673 9533]
 [   0    0    0    0 8235 6348 1933 7952]]


In [10]:
# Feature representation
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

d:\GENAI\DeepLearning\dlenv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:

model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0,  958, 7186, 5673, 9502], dtype=int32)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 421ms/step


array([[[ 1.55304782e-02,  4.89991419e-02, -4.55419198e-02,
          2.91829742e-02, -4.33652885e-02,  2.99628042e-02,
          4.54721190e-02, -1.26728192e-02, -3.72001156e-02,
         -1.34191290e-02],
        [ 1.55304782e-02,  4.89991419e-02, -4.55419198e-02,
          2.91829742e-02, -4.33652885e-02,  2.99628042e-02,
          4.54721190e-02, -1.26728192e-02, -3.72001156e-02,
         -1.34191290e-02],
        [ 1.55304782e-02,  4.89991419e-02, -4.55419198e-02,
          2.91829742e-02, -4.33652885e-02,  2.99628042e-02,
          4.54721190e-02, -1.26728192e-02, -3.72001156e-02,
         -1.34191290e-02],
        [ 1.55304782e-02,  4.89991419e-02, -4.55419198e-02,
          2.91829742e-02, -4.33652885e-02,  2.99628042e-02,
          4.54721190e-02, -1.26728192e-02, -3.72001156e-02,
         -1.34191290e-02],
        [-8.77086073e-03, -4.36082482e-05,  3.24113406e-02,
          3.49997357e-03,  2.76245810e-02, -4.88943718e-02,
          1.19340308e-02, -3.04200407e-02, -3.494299