In [2]:
from tensorflow.keras.preprocessing.text import one_hot


In [3]:
# Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'Iam a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your classes are good',
      ]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'Iam a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your classes are good']

In [5]:
# Define the vocabulary size
voc_size=10000


In [6]:
# One hot representation 
one_hot_repr=[one_hot(sent, voc_size)for sent in sent]
one_hot_repr

[[5074, 1546, 2021, 2853],
 [5074, 1546, 2021, 1574],
 [5074, 6580, 2021, 2031],
 [6186, 2188, 3602, 6791],
 [9987, 3133, 2188, 3602, 4591],
 [7361, 5074, 5807, 2021, 619],
 [7909, 7177, 5467, 3602]]

In [7]:
# word embedding representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing import pad_sequence
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5074 1546 2021 2853]
 [   0    0    0    0 5074 1546 2021 1574]
 [   0    0    0    0 5074 6580 2021 2031]
 [   0    0    0    0 6186 2188 3602 6791]
 [   0    0    0 9987 3133 2188 3602 4591]
 [   0    0    0 7361 5074 5807 2021  619]
 [   0    0    0    0 7909 7177 5467 3602]]


In [10]:
# Feature representation
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [12]:

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 5074, 1546, 2021, 2853])

In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 337ms/step


array([[[ 7.48933479e-03,  8.57748836e-03,  4.33579199e-02,
          3.33167799e-02,  7.93315098e-03, -1.38434656e-02,
         -1.73547976e-02, -3.54902521e-02,  4.00780551e-02,
          4.97566797e-02],
        [ 7.48933479e-03,  8.57748836e-03,  4.33579199e-02,
          3.33167799e-02,  7.93315098e-03, -1.38434656e-02,
         -1.73547976e-02, -3.54902521e-02,  4.00780551e-02,
          4.97566797e-02],
        [ 7.48933479e-03,  8.57748836e-03,  4.33579199e-02,
          3.33167799e-02,  7.93315098e-03, -1.38434656e-02,
         -1.73547976e-02, -3.54902521e-02,  4.00780551e-02,
          4.97566797e-02],
        [ 7.48933479e-03,  8.57748836e-03,  4.33579199e-02,
          3.33167799e-02,  7.93315098e-03, -1.38434656e-02,
         -1.73547976e-02, -3.54902521e-02,  4.00780551e-02,
          4.97566797e-02],
        [ 9.64435190e-03, -4.85790037e-02,  6.23297691e-03,
         -1.54548064e-02,  1.01863369e-02,  4.35434617e-02,
          3.85906734e-02, -3.09578534e-02,  4.321889