In [17]:
from tensorflow.keras.preprocessing.text import one_hot


In [18]:
# Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'Iam a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your classes are good',
      ]

In [19]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'Iam a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your classes are good']

In [20]:
# Define the vocabulary size
voc_size=10000


In [21]:
# One hot representation 
one_hot_repr=[one_hot(sent, voc_size)for sent in sent]
one_hot_repr

[[3860, 4910, 3321, 8672],
 [3860, 4910, 3321, 1603],
 [3860, 4914, 3321, 5567],
 [3546, 4889, 4276, 2679],
 [4525, 9982, 4889, 4276, 5065],
 [3239, 3860, 5234, 3321, 8143],
 [7261, 8409, 8758, 4276]]

In [22]:
# word embedding representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing import pad_sequence
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [23]:
import numpy as np

In [24]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3860 4910 3321 8672]
 [   0    0    0    0 3860 4910 3321 1603]
 [   0    0    0    0 3860 4914 3321 5567]
 [   0    0    0    0 3546 4889 4276 2679]
 [   0    0    0 4525 9982 4889 4276 5065]
 [   0    0    0 3239 3860 5234 3321 8143]
 [   0    0    0    0 7261 8409 8758 4276]]


In [25]:
# Feature representation
dim=10


In [26]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [27]:

model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0, 3860, 4910, 3321, 8672], dtype=int32)

In [29]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 429ms/step


array([[[-3.85295525e-02, -3.24122906e-02,  1.09472759e-02,
          8.53762776e-03, -1.59608945e-02, -1.79618374e-02,
         -1.38325691e-02, -4.42346334e-02, -1.15219466e-02,
         -2.41109729e-02],
        [-3.85295525e-02, -3.24122906e-02,  1.09472759e-02,
          8.53762776e-03, -1.59608945e-02, -1.79618374e-02,
         -1.38325691e-02, -4.42346334e-02, -1.15219466e-02,
         -2.41109729e-02],
        [-3.85295525e-02, -3.24122906e-02,  1.09472759e-02,
          8.53762776e-03, -1.59608945e-02, -1.79618374e-02,
         -1.38325691e-02, -4.42346334e-02, -1.15219466e-02,
         -2.41109729e-02],
        [-3.85295525e-02, -3.24122906e-02,  1.09472759e-02,
          8.53762776e-03, -1.59608945e-02, -1.79618374e-02,
         -1.38325691e-02, -4.42346334e-02, -1.15219466e-02,
         -2.41109729e-02],
        [-1.67860389e-02, -3.40106636e-02, -3.26319709e-02,
         -2.37402320e-02,  5.47461584e-03, -2.64057163e-02,
         -1.72482505e-02,  1.84591301e-02,  2.584027